FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --legacy-peer-deps

COPY public/ ./public/
COPY src/ ./src/
COPY tailwind.config.js postcss.config.js ./

EXPOSE 3000

CMD ["npm", "start"]
