export const CASE_STATUS_VALUES = {
  NO_DATA: 'NO_DATA',
  FDR_UPLOADED: 'FDR_UPLOADED',
  CVR_UPLOADED: 'CVR_UPLOADED',
  READY_FOR_ANALYSIS: 'READY_FOR_ANALYSIS',
  ANALYSIS_RUNNING: 'ANALYSIS_RUNNING',
  ANALYSIS_FAILED: 'ANALYSIS_FAILED',
  FDR_ANALYZED: 'FDR_ANALYZED',
  CVR_ANALYZED: 'CVR_ANALYZED',
  CORRELATION_DONE: 'CORRELATION_DONE',
};

export const CASE_STATUS_LABELS = {
  [CASE_STATUS_VALUES.NO_DATA]: 'No Data Uploaded',
  [CASE_STATUS_VALUES.FDR_UPLOADED]: 'FDR Uploaded',
  [CASE_STATUS_VALUES.CVR_UPLOADED]: 'CVR Uploaded',
  [CASE_STATUS_VALUES.READY_FOR_ANALYSIS]: 'Ready for Analysis',
  [CASE_STATUS_VALUES.ANALYSIS_RUNNING]: 'Analysis Running',
  [CASE_STATUS_VALUES.ANALYSIS_FAILED]: 'Analysis Failed',
  [CASE_STATUS_VALUES.FDR_ANALYZED]: 'FDR Anomaly Analyzed',
  [CASE_STATUS_VALUES.CVR_ANALYZED]: 'CVR Analyzed',
  [CASE_STATUS_VALUES.CORRELATION_DONE]: 'Correlation Complete',
};

export const CASE_STATUS_ORDER = [
  CASE_STATUS_VALUES.NO_DATA,
  CASE_STATUS_VALUES.FDR_UPLOADED,
  CASE_STATUS_VALUES.CVR_UPLOADED,
  CASE_STATUS_VALUES.READY_FOR_ANALYSIS,
  CASE_STATUS_VALUES.ANALYSIS_RUNNING,
  CASE_STATUS_VALUES.ANALYSIS_FAILED,
  CASE_STATUS_VALUES.FDR_ANALYZED,
  CASE_STATUS_VALUES.CVR_ANALYZED,
  CASE_STATUS_VALUES.CORRELATION_DONE,
];

export const FDR_ANALYSIS_STATUS_LABELS = {
  NOT_STARTED: 'FDR not started',
  RUNNING: 'FDR Running',
  COMPLETED: 'FDR Anomaly Analyzed',
  FAILED: 'FDR Failed',
};
